global:
  scrape_interval: 15s

scrape_configs:
  - job_name: fraud_api
    metrics_path: /metrics
    bearer_token_file: /etc/prometheus/token.txt
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: pushgateway
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9091']