name: MLOps Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # monatlich am 1. um 00:00 UTC

jobs:
  drift:
    runs-on: ubuntu-latest
    outputs:
      drift-detected: ${{ steps.detect.outputs.drift }}
    steps:
      - uses: actions/checkout@v3

      - name: Install drift dependencies
        run: pip install pandas scipy joblib

      - name: Run drift detection
        id: detect
        env:
          OLD_DATA_PATH: data/reference_data.csv
          NEW_DATA_PATH: data/latest_data.csv
        run: |
          python drift_detector.py
          # liest drift_result.json, setzt output
          DRIFT=$(jq .drift_detected drift_result.json)
          echo "drift=$DRIFT" >> $GITHUB_OUTPUT

      - name: Upload drift result
        uses: actions/upload-artifact@v4
        with:
          name: drift-result
          path: drift_result.json

  retrain:
    needs: drift
    if: needs.drift.outputs.drift == 'true' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install retrain dependencies
        run: pip install -r requirements.txt mlflow

      - name: Retrain model on latest data
        env:
          TRAIN_DATA_PATH: data/latest_data.csv
        run: python retrain_model.py

      - name: Upload new model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: models/rf_model.pkl

  build-and-push:
    needs: retrain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set lowercase owner name
        shell: bash
        env:
          OWNER: ${{ github.repository_owner }}
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/fraud-api:latest
            ghcr.io/${{ env.OWNER_LC }}/fraud-api:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, Windows]
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      FRAUD_THRESHOLD: "0.4"
      MODEL_PATH: "models/rf_model.pkl"
    steps:
      - name: Pull & restart container locally
        shell: cmd
        run: |
          docker pull ghcr.io/andipfluegl/fraud-api:latest
          docker rm -f fraud_api || echo No existing container
          docker run -d --name fraud_api ^
            --env "API_TOKEN=%API_TOKEN%" ^
            --env "FRAUD_THRESHOLD=%FRAUD_THRESHOLD%" ^
            --env "MODEL_PATH=%MODEL_PATH%" ^
            -p 5000:5000 ^
            ghcr.io/andipfluegl/fraud-api:latest
