name: MLOps Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # monatlich am 1. um 00:00 UTC

jobs:
  drift:
    runs-on: ubuntu-latest
    outputs:
      drift-detected: ${{ steps.detect.outputs.drift }}
    steps:
      - uses: actions/checkout@v3

      - name: Install drift dependencies
        run: pip install pandas scipy joblib

      - name: Run drift detection
        id: detect
        run: |
          python drift_detector.py
          echo "::set-output name=drift::$(jq .drift_detected drift_result.json)"

      - name: Upload drift result
        uses: actions/upload-artifact@v4
        with:
          name: drift-result
          path: drift_result.json

  retrain:
    needs: drift
    # immer retrainen bei Push oder wenn Drift erkannt wurde - muss zurückgesetzt werden!!!! if: needs.drift.outputs.drift == 'true' || github.event_name == 'schedule'
    if: github.event_name == 'push' || needs.drift.outputs.drift == 'true' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install retrain dependencies
        run: pip install -r requirements.txt mlflow

      - name: Retrain model & log to MLflow
        run: python retrain_model.py

      - name: Upload new model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: models/rf_model.pkl

  build-and-push:
    needs: retrain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1) Lowercase owner name in ENV setzen
      - name: Set lowercase owner name
        shell: bash
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          # ${VAR,,} ist Bash‑Syntax für lowercase
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2) Image bauen und mit OWNER_LC taggen
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/fraud-api:latest
            ghcr.io/${{ env.OWNER_LC }}/fraud-api:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, Windows]
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      FRAUD_THRESHOLD: "0.4"
    steps:
      - name: Set lowercase owner
        shell: powershell
        run: |
          $lc = '${{ github.repository_owner }}'.ToLower()
          echo "OWNER_LC=$lc" >> $Env:GITHUB_ENV

      - name: Pull & restart container locally
        shell: cmd
        run: |
          echo Owner: %OWNER_LC%
          docker pull ghcr.io/%OWNER_LC%/fraud-api:latest
          docker rm -f fraud_api || echo No existing container
          docker run -d --name fraud_api --env "API_TOKEN=%API_TOKEN%" --env "FRAUD_THRESHOLD=%FRAUD_THRESHOLD%" -p 5000:5000 ghcr.io/%OWNER_LC%/fraud-api:latest




