name: MLOps Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # monatlich am 1. um 00:00 UTC

jobs:
  drift:
    runs-on: ubuntu-latest
    outputs:
      drift-detected: ${{ steps.detect.outputs.drift }}
    steps:
      - uses: actions/checkout@v3

      # 1) Basis-Dependencies
      - name: Install drift & simulation dependencies
        run: |
          pip install pandas scipy joblib numpy

      # 2) Simuliere 12 Monats-Datensätze
      - name: Generate monthly data
        run: python simulate_data.py

      # 3) Für jeden Monat drift testen
      - name: Run drift detection for each month
        id: detect
        run: |
          for month in $(seq 1 12); do
            echo "→ Testing month $month"
            export NEW_DATA_PATH="data/monthly/new_data_month_${month}.csv"
            # Drift-Detector ausführen und Output sichtbar machen
            python drift_detector.py | tee drift_log_$month.txt

            # Wenn Drift erkannt, Output-Variable setzen und abbrechen
            if grep -q "True" drift_log_$month.txt; then
              echo "drift=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done

          # Wenn kein einziger True, drift=false setzen
          echo "drift=false" >> $GITHUB_OUTPUT

      - name: Upload drift result
        uses: actions/upload-artifact@v4
        with:
          name: drift-result
          path: drift_result.json

  retrain:
    needs: drift
    if: github.event_name == 'push' || needs.drift.outputs.drift == 'true' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install retrain dependencies
        run: pip install -r requirements.txt mlflow

      # Hier das ENV für die simulierten Monatsdaten übergeben:
      - name: Retrain model & log to MLflow
        env:
          TRAIN_DATA_PATH: data/monthly/new_data_month_1.csv   # ← Monat wählen
        run: python retrain_model.py

      - name: Upload new model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: models/rf_model.pkl

  build-and-push:
    needs: retrain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1) Lowercase owner name in ENV setzen
      - name: Set lowercase owner name
        shell: bash
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          # ${VAR,,} ist Bash‑Syntax für lowercase
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2) Image bauen und mit OWNER_LC taggen
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/fraud-api:latest
            ghcr.io/${{ env.OWNER_LC }}/fraud-api:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, Windows]
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      FRAUD_THRESHOLD: "0.4"
      MODEL_PATH: "models/rf_model.pkl"
    steps:
      - name: Pull & restart container locally
        shell: cmd
        run: |
          docker pull ghcr.io/andipfluegl/fraud-api:latest
          docker rm -f fraud_api || echo No existing container
          docker run -d --name fraud_api ^
            --env "API_TOKEN=%API_TOKEN%" ^
            --env "FRAUD_THRESHOLD=%FRAUD_THRESHOLD%" ^
            --env "MODEL_PATH=%MODEL_PATH%" ^
            -p 5000:5000 ^
            ghcr.io/andipfluegl/fraud-api:latest


